# Generated by Django 5.2.7 on 2025-10-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(editable=False)),
                ('response_time', models.FloatField(editable=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='monitor.server')),
            ],
        ),
    ]
