# Generated by Django 5.2.7 on 2025-10-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklog',
            options={'verbose_name_plural': 'Check Logs'},
        ),
    ]
