# Generated by Django 5.2.7 on 2025-10-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_checklog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklog',
            name='error',
            field=models.CharField(default='', editable=False),
        ),
    ]
