# Generated by Django 5.2.7 on 2025-10-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_checklog_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklog',
            name='error',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='response_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.server'),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='status_code',
            field=models.IntegerField(),
        ),
    ]
