# Generated by Django 5.2.7 on 2025-10-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_checklog_error_alter_checklog_response_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_interval_seconds', models.PositiveIntegerField(default=300)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
